### ISSUE TITLE
AttributeError: 'GatewayStub' object has no attribute 'CreateWorkflowInstance'

### ISSUE THREAD

**Issue by umesh-kushwaha** [berndruecker/kafka-connect-zeebe-benchmark#3]
I am trying to use this repository for bench marking. When I run the sample then I got the below error  

`AttributeError: 'GatewayStub' object has no attribute 'CreateWorkflowInstance'
`

**Comment by berndruecker** [comment]
Hi Umesh - the benchmark project is currently unmaintained - and it relates to an outdated Zeebe version (https://github.com/berndruecker/kafka-connect-zeebe-benchmark/blob/master/docker-compose/docker-compose.yml#L5. Depending on which Python client you use exactly this does not fit together.

I recommend upgrading to the latest versions (zeebe, kafka-connect-zeebe and Kafka) and give it another try. 

I will add a not about the lifecycle state of this project in the readme
